version: "3.1"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./scripts/travel_agency_hotel.sql:/docker-entrypoint-initdb.d/travel_agency_hotel.sql
    healthcheck:
      test: "mysqladmin ping -h localhost -u root --password=example"
      timeout: 5s
      retries: 10

  config-server:
    image: config-server

  eureka-server:
    image: eureka-server
    environment:
      CONFIG_HOST: config-server
      CONFIG_PORT: 8888

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: hotel-ms
    environment:
      CONFIG_HOST: config-server
      CONFIG_PORT: 8888
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: example
      EUREKA_HOST: eureka-server
      EUREKA_PORT: 8761
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy
