server:
  port: 8080

spring:
  application:
    name: courses-ms
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/courses
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD}
