version: "3.1"

services:
  courses-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./courses-ms/scripts/courses.sql:/docker-entrypoint-initdb.d/courses.sql
    healthcheck:
      test: "mysqladmin ping -h localhost -u root --password=example"
      timeout: 5s
      retries: 10

  courses-ms:
    build:
      context: courses-ms
      dockerfile: Dockerfile
    image: courses-ms
    environment:
      MYSQL_HOST: courses-db
      MYSQL_PORT: 3306
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: example
    ports:
      - "8081:8080"
    depends_on:
      courses-db:
        condition: service_healthy

  training-ms:
    build:
      context: training-ms
      dockerfile: Dockerfile
    image: training-ms
    environment:
      COURSES_HOST: courses-ms
      COURSES_PORT: 8080
    ports:
      - "8082:8080"

  adminer:
    image: adminer
    ports:
      - "8001:8080"
