version: "3.1"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./scripts/travel_agency_flight.sql:/docker-entrypoint-initdb.d/travel_agency_flight.sql
    healthcheck:
      test: "mysqladmin ping -h localhost -u root --password=example"
      timeout: 5s
      retries: 10

  kafka:
    image: bitnami/kafka
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    healthcheck:
      test: "kafka-topics.sh --bootstrap-server 127.0.0.1:9092 --list"
      timeout: 5s
      retries: 10

  config-server:
    image: config-server

  eureka-server:
    image: eureka-server
    environment:
      CONFIG_HOST: config-server
      CONFIG_PORT: 8888

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: flight-ms
    environment:
      CONFIG_HOST: config-server
      CONFIG_PORT: 8888
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: example
      EUREKA_HOST: eureka-server
      EUREKA_PORT: 8761
      KAFKA_HOST: kafka
      KAFKA_PORT: 9092
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy
      kafka:
        condition: service_healthy
