server:
  port: 9000

spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: courses-ms
          uri: lb://courses-ms
          predicates:
            - Path=/courses/**
          filters:
            - RewritePath=/courses, /
        - id: training-ms
          uri: lb://training-ms
          predicates:
            - Path=/trainings/**
          filters:
            - RewritePath=/trainings, /

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: false
