#server:
#  port: 8761

spring:
  application:
    name: eureka-server
  config:
    import: configserver:http://${CONFIG_HOST:localhost}:${CONFIG_PORT:8888}?fail-fast=true&max-attempts=10

#eureka:
#  client:
#    registerWithEureka: false
#    fetch-registry: false
